"""NHL94 high-level action intents."""

HOCKEY_INTENT_DPAD_ACTIONS = (
    'NOOP',
    'CARRY_PUCK',
    'NORMAL_SHOOT',
    'SLAPSHOT',
    'ONE_TIMER',
    'POKE_CHECK',
    'CHANGE_PLAYER',
    'PASS_TEAMMATE_1',
    'PASS_TEAMMATE_2',
    'PASS_TEAMMATE_3',
    'PASS_TEAMMATE_4',
)

HOCKEY_INTENT_DPAD_ACTION_SPACE = [len(HOCKEY_INTENT_DPAD_ACTIONS), 2, 2, 2, 2, 2]
HOCKEY_INTENT_NOOP = HOCKEY_INTENT_DPAD_ACTIONS.index('NOOP')
HOCKEY_INTENT_CARRY_PUCK = HOCKEY_INTENT_DPAD_ACTIONS.index('CARRY_PUCK')
HOCKEY_INTENT_NORMAL_SHOOT = HOCKEY_INTENT_DPAD_ACTIONS.index('NORMAL_SHOOT')
HOCKEY_INTENT_SLAPSHOT = HOCKEY_INTENT_DPAD_ACTIONS.index('SLAPSHOT')
HOCKEY_INTENT_ONE_TIMER = HOCKEY_INTENT_DPAD_ACTIONS.index('ONE_TIMER')
HOCKEY_INTENT_POKE_CHECK = HOCKEY_INTENT_DPAD_ACTIONS.index('POKE_CHECK')
HOCKEY_INTENT_CHANGE_PLAYER = HOCKEY_INTENT_DPAD_ACTIONS.index('CHANGE_PLAYER')
HOCKEY_INTENT_PASS_START = HOCKEY_INTENT_DPAD_ACTIONS.index('PASS_TEAMMATE_1')
